export { abi as ERC20 } from './erc20.json'
export { abi as Otto } from './Otto.json'
export { abi as OttopiaPortalCreator } from './OttopiaPortalCreator.json'
export { abi as OttoSummoner } from './OttoSummoner.json'
export { abi as OttoItemAbi } from './OttoItem.json'
