export { abi as ERC20Abi } from './erc20.json'
export { abi as OttoAbi } from './Otto.json'
export { abi as OttopiaPortalCreatorAbi } from './OttopiaPortalCreator.json'
export { abi as OttoSummonerAbi } from './OttoSummoner.json'
export { abi as OttoItemAbi } from './OttoItem.json'
export { abi as OttopiaStoreAbi } from './OttopiaStore.json'
export { abi as IOttoItemFactoryAbi } from './IOttoItemFactory.json'
