/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOttoItemFactory__factory } from "./IOttoItemFactory__factory";
export { Otto__factory } from "./Otto__factory";
export { OttoItem__factory } from "./OttoItem__factory";
export { OttoSummoner__factory } from "./OttoSummoner__factory";
export { OttopiaPortalCreator__factory } from "./OttopiaPortalCreator__factory";
export { OttopiaStore__factory } from "./OttopiaStore__factory";
export { Erc20__factory } from "./Erc20__factory";
