import { BundleName } from '../consts'
import { GeneralAssetsBundle } from './bundle'

export const adventure = new GeneralAssetsBundle(BundleName.AdventurePage, [
  '/images/adventure/EXP.png',
  '/images/adventure/adventure_journal_bg.png',
  '/images/adventure/adventure_location_1_bg_image.png',
  '/images/adventure/adventure_location_1_bg_image_black.jpe',
  '/images/adventure/adventure_location_1_image.png',
  '/images/adventure/adventure_location_2_bg_image.jpe',
  '/images/adventure/adventure_location_2_bg_image_black.jpe',
  '/images/adventure/adventure_location_2_image.png',
  '/images/adventure/adventure_location_3_bg_image.jpe',
  '/images/adventure/adventure_location_3_bg_image_black.jpe',
  '/images/adventure/adventure_location_3_image.png',
  '/images/adventure/adventure_location_4_bg_image.jpe',
  '/images/adventure/adventure_location_4_bg_image_black.jpe',
  '/images/adventure/adventure_location_4_image.png',
  '/images/adventure/adventure_location_5_bg_image.jpe',
  '/images/adventure/adventure_location_5_bg_image_black.jpe',
  '/images/adventure/adventure_location_5_image.png',
  '/images/adventure/ap.png',
  '/images/adventure/arrow.svg',
  '/images/adventure/chain.png',
  '/images/adventure/continue.png',
  '/images/adventure/hot-spring-large.jpg',
  '/images/adventure/hot-spring.jpg',
  '/images/adventure/kodama-revive.gif',
  '/images/adventure/location_name.png',
  '/images/adventure/lock.png',
  '/images/adventure/lock.svg',
  '/images/adventure/ribbon.png',
  '/images/adventure/share.png',
  '/images/adventure/skull.png',
  '/images/adventure/speed-up-potion.png',
  '/images/adventure/tooltipicon.png',
  '/images/adventure/map.jpg',
])
