name: Deploy

on:
  push:
    branches:
      - main

env:
  GCR: us.gcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Set env variables
        run: |
          echo "IMAGE_NAME=$GCR/$GCP_PROJECT/otter-app" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_DISCORD_CLIENT_ID=${{ secrets.NEXT_PUBLIC_DISCORD_CLIENT_ID }}" >> $GITHUB_ENV

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: 'Push images'
        run: |
          gcloud auth configure-docker
          ./scripts/dockerbuild.sh $BRANCH_NAME
          docker push ${IMAGE_NAME} --all-tags
